name: ci-checks

on: [pull_request]

jobs:
  frontend:
    name: frontend
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16.x'
    - name: install
      run: |
        yarn install
    - name: package windows
      run: |
        yarn run package-win
    - name: Upload webpack build
      uses: actions/upload-artifact@v2
      with:
        name: windows
        path: |
          release/*.exe
